-- 코드를 입력하세요
SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD as B
join USED_GOODS_REPLY as R
on B.BOARD_ID = R.BOARD_ID
# where year(B.CREATED_DATE) = 2022
# and month(B.CREATED_DATE) = 10
WHERE B.CREATED_DATE >= '2022-10-01' AND B.CREATED_DATE < '2022-11-01'
order by R.CREATED_DATE, B.TITLE;